#!/bin/bash
APP_VERSION="1.0.0"
echo "=============================="
echo " Demo App v${APP_VERSION}"
echo "=============================="
echo "Host     : $(hostname)"
echo "Date     : $(date)"
echo "Uptime   : $(uptime -p)"
echo "Kernel   : $(uname -r)"
echo "Disk     : $(df -h / | awk 'NR==2{print $5 " used"}')"
echo "Memory   : $(free -h | awk '/Mem:/{print $3 "/" $2}')"
echo "User     : $(whoami)"
echo "=============================="
echo "App started successfully!"
